# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest

  tools:
    python: "latest"

python:
  install:
    # Avoids fragmentation of the dependencies across multiple files,
    # and makes it easier to maintain the dependencies in one place.
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
