%% SPDX-License-Identifier: CC-BY-4.0
classDiagram

class xen_domctl {
    +uint32_t cmd
    +uint32_t interface_version
    +uint32_t domain
    +xen_domctl_claim_memory
}

class xen_domctl_claim_memory {
    +memory_claim_t* claims
    +uint32_t nr_claims
    +uint32_t pad
}

class memory_claim_t {
    +uint64_aligned_t pages
    +uint32_t node
    +uint32_t pad
}

class xc_domain_claim_memory["xc_domain_claim_memory()"] {
    +xc_interface* xch
    +uint32_t domid
    +uint32_t nr_claims
    +memory_claim_t* claims
}

class page_alloc_globals["xen/common/page_alloc.c"] {
    +unsigned long outstanding_claims
    +unsigned long node_outstanding_claims[]
}

class claim["DOMCTL_claim_memory"] {
    +int claim_memory(d, uinfo)
    +int domain_set_outstanding_pages(d, pages, node)
}

class domain["struct domain"] {
    +unsigned_int outstanding_pages
    +nodeid_t claim_node
}

xen_domctl_claim_memory o--> memory_claim_t
xen_domctl o--> xen_domctl_claim_memory
xc_domain_claim_memory ..> xen_domctl : populates
xc_domain_claim_memory ..> claim : calls via <tt>do_domctl()</tt>
claim ..> xen_domctl_claim_memory : reads
claim ..> domain : sets
claim ..> page_alloc_globals : updates outstanding claims
