# -*- coding: utf-8 -*-
# SPDX-License-Identifier: CC-BY-4.0
#
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import sphinx

project = u'Xen'
copyright = u'2019-%Y, The Xen development community'
author = u'The Xen development community'

if sphinx.version_info < (8, 1):
    from datetime import datetime
    copyright = datetime.today().strftime(copyright)

# Pull the Xen version straight out of the Makefile
try:
    xen_ver = xen_subver = xen_extra = None

    for line in open(u"../xen/Makefile"):
        if line.startswith(u"export XEN_VERSION"):
            xen_ver = line.split(u"=")[1].strip()
        elif line.startswith(u"export XEN_SUBVERSION"):
            xen_subver = line.split(u"=")[1].strip()
        elif line.startswith(u"export XEN_EXTRAVERSION"):
            xen_extra = line.split(u"=")[1].split(u"$", 1)[0].strip()
except:
    pass
finally:
    if xen_ver and xen_subver and xen_extra:
        version = xen_ver + u"." + xen_subver
        release = version + xen_extra
    else:
        version = release = u"unknown version"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = "7.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx.ext.autosectionlabel"]

try:
    import sphinxcontrib.mermaid

    extensions.append("sphinxcontrib.mermaid")
except ImportError:
    pass


def on_build_finished(app, exception):
    if exception:
        return

    common_install = """
        Alternatively, you can use pipx to install sphinx and the needed
        extras in an isolated environment with:\n
            pipx install sphinx
            pipx runpip sphinx install -r docs/requirements.txt\n
        Or, use `make -C docs sphinx-env-build` to build the documentation
        in a suitable Python environment with all dependencies.\n"""

    # See https://sphinx-book-theme.readthedocs.io for more info:
    if not sys.modules.get("sphinx_book_theme"):
        sys.stderr.write("""
        To fix rendering the HTML theme, install `sphinx_book_theme` in
        your Python venv. On Debian-based systems, you can install it with:\n
            sudo apt install python3-sphinx-book-theme""" + common_install)

    # See https://sphinxcontrib-mermaid-demo.readthedocs.io
    # or  https://github.com/mgaitan/sphinxcontrib-mermaid for more info:
    if not sys.modules.get("sphinxcontrib.mermaid"):
        sys.stderr.write("""
        To fix rendering mermaid diagrams, install `sphinxcontrib.mermaid` in
        your Python venv. On Debian-based systems, you can install it with:\n
            sudo apt install python3-sphinxcontrib-mermaid""" + common_install)

    # See https://github.com/sphinx-doc/sphinx-autobuild#readme for more info:
    try:
        import sphinx_autobuild
    except ImportError:
        print("The generated documentation is available at:")
        print(f"file://{app.outdir}/index.html")
        print("You can also serve it locally with:")
        print(f"  (cd {app.outdir}; python -m http.server)")
        print("To auto-rebuild and auto-refresh on changes, install")
        print("`sphinx-autobuild` in your Python venv and run:")
        print(" sphinx-autobuild docs docs/sphinx/html")
        print("Or simply use `make -C docs sphinx-autobuild` to build & serve")


def setup(app):
    app.connect("build-finished", on_build_finished)


# Extension options

# sphinxcontrib.mermaid
mermaid_init_js = """
mermaid.initialize({ startOnLoad: true });
"""

# sphinx.ext.autosectionlabel
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'sphinx/output', 'Thumbs.db', '.DS_Store', '.sphinx']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

primary_domain = 'c'
highlight_language = 'none'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_title = f"Xen Hypervisor {version} Documentation"
html_logo = "_static/logo-xen.svg"
html_favicon = "_static/favicon-xen-32x32.png"

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
try:
    import sphinx_book_theme

    html_theme = 'sphinx_book_theme'
    # Theme options are theme-specific and customize the look and feel
    # of a theme further. For a list of options available for each theme,
    # see the documentation of that theme. e.g. for sphinx_book_theme, see
    # https://sphinx-book-theme.readthedocs.io/en/latest/configure.html#options
    html_theme_options = {
        "logo": {
            "text": f"Xen Hypervisor {version}",
            "image_light": html_logo,
            "image_dark": "_static/logo-xen-reverse.svg",
        },
        "home_page_in_toc": False,
        # Depth of the table of contents tree to show in the right sidebar
        "show_toc_level": 3,
        "repository_url": "https://github.com/xen-project/xen",
        "use_repository_button": True,
    }
except ImportError:
    sys.stderr.write(
        "sphinx_book_theme was not found, falling back to the default theme.\n"
    )


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Xendoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Xen.tex', u'Xen Documentation',
     u'The Xen development community', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'xen', u'Xen Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Xen', u'Xen Documentation',
     author, 'Xen', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']
